version: '3.9'

services:

  # initializer:
  #   image: alpine3.18
  #   container_name: alpine3.18
  #   restart: "no"
  #   entrypoint: |
  #     /bin/sh -c "chown 8000:8000 /duser"
  #   volumes:
  #     - ./data/duser:/duser

  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env